### ISSUE TITLE
[bug]:  firebase configure does not generate firebase_app_id_file.json

### ISSUE THREAD

**Issue by takumi-pac** [invertase/flutterfire_cli#327] opened 2024-07-14 10:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.13.0

### Flutter Doctor Output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)            
    ! Error: Browsing on the local area network for iPhone (53). Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

### Description

I encountered an issue when running the firebase configure command. Despite following the instructions and running the command as specified, the expected firebase_app_id_file.json file is not generated. This file is crucial for my Flutter project, and its absence is causing build errors related to Firebase configuration.

Interestingly, the firebase_app_id_file.json was generated correctly with previous versions of Flutter. However, after updating to Flutter 3.22.2, the file is no longer being created.

### Steps to reproduce

Run firebase configure in the terminal.
Check the project directory for the firebase_app_id_file.json

### Expected behavior

The firebase configure command should generate the firebase_app_id_file.json file in the project directory.

### Additional context and comments

The firebase_app_id_file.json file is not generated, leading to Firebase configuration errors in the Flutter project.

Flutter and Firebase Versions:

Flutter version: 3.22.2
Firebase CLI version: 1.0.0
Environment:

Operating System: macOS Sonoma 14.5
Additional Context:

This issue started occurring after upgrading to Flutter 3.22.2. Previously, the file was generated correctly with earlier versions of Flutter.

**Comment by vanyasem** [comment] 2024-08-02 02:41
duplicate of https://github.com/invertase/flutterfire_cli/issues/280

**Comment by maRci002** [comment] 2024-08-26 12:52
Since v1.0.0, the files `firebase_app_id_file.json` and `GoogleService-Info.plist` are not being generated; however, `firebase.json` is generated at the root of the project. @russellwheatley, can you help me understand why this is happening?

This is my command
```log
flutterfire configure ^
--project xxxxx-app-dev-a123a123 ^
--out lib/app/firebase_options/dev/firebase_options.dart ^
-i com.example.xxxxxApp.dev ^
--ios-out ios/firebase_config/dev ^
-a com.example.xxxxx_app.dev ^
--android-out android/app/src/dev ^
--platforms "android,ios,web"
```

**Comment by vanyasem** [comment] 2024-08-26 14:11
@maRci002 
this is a duplicate of https://github.com/invertase/flutterfire_cli/issues/280

your question has already been answered there

**Comment by russellwheatley** [comment] 2024-08-27 08:41
As mentioned, `firebase_app_id_file.json` is no longer generated in your src code, but is hidden in `/.dart_tools/` to stop polluting your workspace 👍

**Closed by russellwheatley** 2024-08-27 08:41 UTC
Labels: bug, triage
