### ISSUE TITLE
FormatException error with flutterfire configure 

### ISSUE THREAD

**Issue by Smartiiez** [invertase/flutterfire_cli#30] opened 2022-01-01 10:09 UTC
Hi 👋,

I got FormatException when I run the flutter configure command line :
```
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:523:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:506:36)
#4      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#5      getProjects (package:flutterfire_cli/src/firebase.dart:114:7)
<asynchronous suspension>
#6      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:159:24)
<asynchronous suspension>
#7      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:227:37)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///Users/home/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:34:5)
<asynchronous suspension>
```

**Comment by chonghorizons** [comment] 2022-01-04 21:15
I had a similar issue (#33), but it was solved with the two commands here: https://github.com/invertase/flutterfire_cli/issues/27#issuecomment-1002965081

Maybe that will help.

**Comment by Smartiiez** [comment] 2022-01-10 19:34
Thanks for the answer but I still get the error 😓

**Comment by mhussaines** [comment] 2022-02-01 06:45
Thanks for the answer but I still get the error too.

**Comment by gaikwad2udit** [comment] 2022-02-06 10:38
same issue

**Comment by gaikwad2udit** [comment] 2022-02-06 10:40
> Thanks for the answer but I still get the error 😓

did you find the solution ?

**Comment by mhussaines** [comment] 2022-02-06 12:26
Yes, I just updated the firebase_message version in pubspec.yaml file and it started working without any code change. 
 

Mohammad Hussain Anwar
Computer Programmer (iOS Developer)
Excellent Solutions
Tel:      +966 11 4196560 Ext-135
Mob:    +966-53-6256339
Email:  ***@***.***
Regards,

**Comment by Nico04** [comment] 2022-02-23 15:42
Same issue here on Windows.
I installed the firebase CLI from the standalone version, moved to my project folder and rename it to firebase.exe
But when using flutterfire command it throws FormatException
I've tried few comments found on github, without any luck

**Comment by tomlaws** [comment] 2022-04-16 11:34
In my case installing from npm solved the issue.

`npm install -g firebase-tools`

**Comment by SpaceBug199** [comment] 2022-06-12 08:15
I had the same issue on macOS with npm installation of firebase-tools. 
My problem was that npm installed firebase-tools version 8.0.2. and the current version was 11.0.1. 

To check your version run `firebase --version`

I have solved this issue by running 
`curl -sL firebase.tools | upgrade=true bash`

**Comment by bastaware** [comment] 2022-08-12 21:17
> current

This helped me on Mac OSX. Though I needed to upgrade firebase.tools using npm. First I had to upgrade **node**, also using npm.

But when I ran `flutterfire configure`, I got a new error: **i Found 0 Firebase projects**.

This was solved by logging out and into Firebase (`firebase logout, firebase login`)

**Comment by vincekruger** [comment] 2022-09-17 11:44
Urg. I'm getting this error all the time despite all the suggestions on many threads and comments. :(

**Comment by ArAmM7** [comment] 2022-09-25 18:22
For anyone wondering what works on windows, I used cmd as admin to run the flutterfire configure command and it worked. I am using the npm version of firebase cli.

**Comment by russellwheatley** [comment] 2022-09-28 09:34
@Smartiiez - are you running in a windows environment? 

Also same question to everyone who is experiencing this problem, @here?

**Comment by FDuhen** [comment] 2022-09-29 06:43
Updating this issue with a slightly different problem, but the root cause may be the same.

firebase-tools version: 11.11.0  
flutterfire version : 0.2.6  
flutter version : tried with 3.0.1 and 3.3.2  
dart version : 2.18.2   

**Stacktrace**:  

```
⠹ Fetching available Firebase projects...                                                                                                                          
Unhandled exception:
FormatException: Unexpected end of input (at line 1981, character 9)
      },
        ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#5      getProjects (package:flutterfire_cli/src/firebase.dart:114:20)
<asynchronous suspension>
#6      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:278:24)
<asynchronous suspension>
#7      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:368:37)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///Users/fduhen/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.6/bin/flutterfire.dart:57:5)
<asynchronous suspension>
╭─fduhen@MacBook-Pro ~/Workspace/Front/Flutter/ahs-provider--flutter ‹feat/notifs●› 
╰─$ flutterfire configure --project=ahs-provider-mobile-uat                                                                                                  255 ↵
⠸ Fetching available Firebase projects...                                                                                                                          
Unhandled exception:
FormatException: Unexpected end of input (at line 1981, character 9)
      },
        ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#5      getProjects (package:flutterfire_cli/src/firebase.dart:114:20)
<asynchronous suspension>
#6      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:278:24)
<asynchronous suspension>
#7      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:368:37)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///Users/fduhen/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.2.6/bin/flutterfire.dart:57:5)
<asynchronous suspension>
```

The fixes I've tried so far without any success :  
- Reinstalling firebase-tools
- Deactivating/reactivating flutterfire_cli and reconnecting
- Updating Dart

**Comment by normidar** [comment] 2022-10-01 15:59
I have the same issue here(using macOS M1):

I can not fix it after these :

- flutter clean
- install firebase-tools latest version
- upgrade flutter & dart
- upgrade packages about firebase
- close vscode and reopen

```
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      FirebaseAndroidOptions.projectIdFromFileContents (package:flutterfire_cli/src/firebase/firebase_android_options.dart:29:29)
#5      FirebaseAndroidGradlePlugins.applyGoogleServicesPlugin (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:101:50)
<asynchronous suspension>
#6      FirebaseAndroidGradlePlugins.apply (package:flutterfire_cli/src/firebase/firebase_android_gradle_plugins.dart:240:5)
<asynchronous suspension>
```

**Comment by normidar** [comment] 2022-10-01 16:31
I saw the `flutterfire` code, I think the problem is my `google-services.json` file, I reinstalled it and fixed this error.

**Comment by syeds-git** [comment] 2022-12-04 05:28
> I checked the `flutterfire_cli` code, I think the problem is my `google-services.json` file, I redownloaded it and fixed this error.
> 
> see: https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/firebase/firebase_android_gradle_plugins.dart#L67

So this happened to me in Dec 2022 after I attempted to add firebase_auth: ^4.1.5. I had first installed and tested the following

  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6

and then proceeded on to add firebase_auth and then as instructed in the official docs ran the flutterfire configure. This resulted in the above error. I checked the google-services.json file and noticed that it was wiped out. So I downloaded it manually and resolved the issue.

**Comment by cosmopool** [comment] 2023-01-13 11:25
For me, on a mac m1:

- `sudo gem install xcodeproj` 
- `curl -sL firebase.tools | upgrade=true bash`
- `rm android/app/google-services.json`

Solved the issue.

**Comment by fullflash** [comment] 2023-01-27 21:39
> For me, on a mac m1:
> 
> * `sudo gem install xcodeproj`
> * `curl -sL firebase.tools | upgrade=true bash`
> * `rm android/app/google-services.json`
> 
> Solved the issue.

also firebase login --reauth

**Comment by nsweatlas** [comment] 2023-02-08 17:59
> For anyone wondering what works on windows, I used cmd as admin to run the flutterfire configure command and it worked. I am using the npm version of firebase cli.

This worked for me, thanks! I had issues running it in the Firebase CLI 😅

Just to document for myself (Windows 10), when running 'flutterfire configure', I had 'FirebaseCommandException' issue earlier.
Renaming a copy of 'firebase-tools-instant-win.exe' to 'firebase.exe' didn't work for me, turns out it was as simple as running `'npm get prefix'` and adding that to Path in _System variables_. Then I ran into this same issue as parent thread, which is solved (for me) by simply running in command line instead 😅 thanks again!

**Comment by nilooy** [comment] 2023-03-10 15:48
deleting `android/app/google-services.json`  worked for me
```sh
rm android/app/google-services.json
```

**Comment by erlangparasu** [comment] 2023-05-09 05:51
> deleting `android/app/google-services.json` worked for me
> 
> ```shell
> rm android/app/google-services.json
> ```

@nilooy Thanks works for me too

**Comment by niceman114** [comment] 2023-05-20 08:50
> deleting `android/app/google-services.json` worked for me
> 
> ```shell
> rm android/app/google-services.json
> ```

It works for me. thx!

**Comment by VinGitonga** [comment] 2023-05-27 08:20
> ```shell
> rm android/app/google-services.json
> ```

This also worked for me

**Comment by asad-mansoor-dev** [comment] 2023-06-01 13:58
I did following steps and it worked for me.

- Run flutter doctor, and resolved issues.
- Installed rebnv
- Installed Cocoapods (Learned from ChatGPT the steps to install Cocoapods through rebnv)
- Installed xcodeproj `sudo gem install xcodeproj`
- Restart IDE 
- logout and login from firebase.
- Lastly configure Firebase Project `flutterfire configure`

**Comment by pnhoanglong** [comment] 2023-08-30 08:44
> rm android/app/google-services.json
It save my life

**Comment by WhiteRiverBay** [comment] 2023-08-30 17:27
> 

rm android/app/google-services.json
workd

**Comment by WhiteRiverBay** [comment] 2023-08-30 17:28
> For me, on a mac m1:
> 
> * `sudo gem install xcodeproj`
> * `curl -sL firebase.tools | upgrade=true bash`
> * `rm android/app/google-services.json`
> 
> Solved the issue.

rm android/app/google-services.json

works for me , thank you

**Comment by russellwheatley** [comment] 2023-09-14 08:16
Hey folks, we have cut the latest dev release which you can install like so:

```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite

```

If you also install the latest Firebase CLI `npm i -g firebase-tools`, they have a fix for malformed JSON responses (what FlutterFire CLI uses under the hood) which they have just released 👍. This ought to fix @Smartiiez's  issue.

**Comment by russellwheatley** [comment] 2023-10-19 10:57
Closing out as this ought to be fixed with the latest Firebase CLI noted above.

**Closed by russellwheatley** 2023-10-19 10:57 UTC
Labels: hacktoberfest
