### ISSUE TITLE
Flutter Fire CLI output and input broken

### ISSUE THREAD

**Issue by thejohanmagnusson** [invertase/flutterfire_cli#18] opened 2021-12-19 20:54 UTC
I have tried to initialize my current project and a new clean project but the output and input in the terminal is broken for me.

When I run flutterfire configure it starts fetching the available projects but it behaves strangely, this is the output.

?[A?[2K⠦ Fetching available Firebase projects...
?[A?[2K⠧ Fetching available Firebase projects...
?[A?[2K⠇ Fetching available Firebase projects...
?[A?[2K⠏ Fetching available Firebase projects...
?[A?[2K⠋ Fetching available Firebase projects...
?[A?[2K⠙ Fetching available Firebase projects...
?[A?[2K⠹ Fetching available Firebase projects...
?[A?[2Ki Found 2 Firebase projects.
?[?25h
?[?25l
  example-staging (example-staging)
  &#x3C;create a new project&#x3E;

 I’m not able to input anything when it is done fetching and I have to terminate the CLI. Running the firebase CLI is working fine. It also finds two projects but it only shows one of them.

I'm on Windows 10, version 21H2

**Comment by Salakar** [comment] 2022-01-07 16:47
Closing as duplicate of #34

**Closed by Salakar** 2022-01-07 16:47 UTC

**Comment by molaktycoon** [comment] 2022-05-11 16:42
This issue as not been solve.
