### ISSUE TITLE
[bug]:  firebase_app_id_file.json not created after running flutterfire configure 

### ISSUE THREAD

**Issue by chilkurisainath** [invertase/flutterfire_cli#280] opened 2024-04-12 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

1.0.0

### Firebase Tools version

13.4.1

### Flutter Doctor Output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2 23C64 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!

### Description

1. Run flutterfire configure
 output: Firebase configuration file lib/firebase_options.dart generated successfully with the following Firebase apps:
 Platform  Firebase App Id
  android   ********************************
  ios       ********************************
  
  While creating the build:
  Error:
   **error: Unable to read file at path $PROJECT/ios/firebase_app_id_file.json**

### Steps to reproduce

flutterfire configure --project=$PROJECT_ID --ios-bundle-id=$PACKAGE_NAME --android-app-id=$PACKAGE_NAME --macos-bundle-id=$PACKAGE_NAME --platforms=$PLATFORMS --token=$TOKEN

### Expected behavior

firebase_app_id_file.json should be generated

**Comment by alfalcon90** [comment] 2024-04-12 18:38
This just broke our Codemagic CI setup since it makes the iOS build phase fail. It looks like it works fine in version 0.2.7 so you can downgrade/pin the version by using `dart pub global activate flutterfire_cli ^0.2.7` while this is being fixed.

**Comment by Deepnaik4** [comment] 2024-04-14 15:14
Agreed we face the same with our pipeline. We downgraded the Flutter Fire version to 0.2.7, which fixed the issue.

**Comment by aniketcodebase** [comment] 2024-04-16 05:43
Not sure if the firebase_app_id_file.json is required anymore starting 1.0.0? but not mentioned anywhere in docs/changelog for 1.0.0 and the build is failing for you guys. so assuming something is wrong and downgrading to 0.2.7 seems to be the way to go for now.

**Comment by aniketcodebase** [comment] 2024-04-16 06:08
few observations -
- flutterfire 1.0.0 inserts the new config in firebase.json 

```
{
    "flutter": {
        "platforms": {
            "android": {
                "default": {
                    "projectId": "<>",
                    "appId": "<>",
                    "fileOutput": "android/app/google-services.json"
                }
            },
            "ios": {
                "default": {
                    "projectId": "<>",
                    "appId": "<>",
                    "uploadDebugSymbols": true,
                    "fileOutput": "ios/Runner/GoogleService-Info.plist"
                }
            },
            "dart": {
                "lib/firebase_options.dart": {
                    "projectId": "<>",
                    "configurations": {
                        "android": "<>",
                        "ios": "<>",
                        "web": "<>"
                    }
                }
            }
        }
    }
}
```

- it generates the app_id_file.json under /.dart_tools/flutterfire/ios/default/<project_name>/

```
{
    "GOOGLE_APP_ID": "<>",
    "FIREBASE_PROJECT_ID": "<>"
}
```

**Comment by russellwheatley** [comment] 2024-04-18 08:38
@chilkurisainath - `flutterfire configure` no longer writes `firebase_app_id_file.json` file to the root of your project. It is now hidden in `/.dart_tools/` path (as correctly identified by @aniketcodebase) so we track each file for each build mode/flavor and to stop polluting your workspace.

I don't understand where this error is coming from:
```
error: Unable to read file at path $PROJECT/ios/firebase_app_id_file.json
```

Is this from running `flutter run`?

 It has no concept of this file, the only time this file is even read is in the crashlytics upload symbol script but it does not throw an error, it safely exits when it isn't there: https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/ios/crashlytics_add_upload_symbols#L46

**Comment by sharathguvvala** [comment] 2024-04-30 06:19
@russellwheatley I get this warning, when i run `pod install` inside my ios folder.

> Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.

And I see this missing dsym file error in firebase console, I also tried adding it manually from archives, but still that one file is missing, earlier all were missing before adding the zip from archives

```
flutterfire 1.0.0
firebase_crashlytics: 3.5.4
```

<img width="1070" alt="Screenshot 2024-04-30 at 11 43 55" src="https://github.com/invertase/flutterfire_cli/assets/76590740/3ad2ca70-6dce-41d7-9dd3-e9ab4ee88298">

**Comment by TatsuUkraine** [comment] 2024-05-11 13:58
I can be wrong but I think starting from v1 it shouldn't generate this file. You probably need to cleanup your iOS project file, since in a past cli tool was inserting a different task that relying on this old JSON file. In v1 cli tool generates different JSON file and a different execution command

**Comment by TatsuUkraine** [comment] 2024-05-11 14:04
You can open your project in xcode, go to tab with Build phases (I think it's called like that), remove any commands related to firebase (each should have "firebase" in the name), and run cli configure command one more time

**Comment by russellwheatley** [comment] 2024-05-13 07:43
@TatsuUkraine - yes, this is correct. Remove any FlutterFire related scripts in the build phases and rerun (using latest FlutterFire CLI) which will reinsert the latest build phase scripts for you. I'm closing out as this is not a bug.

**Closed by russellwheatley** 2024-05-13 07:43 UTC
Labels: bug, question

**Comment by sharathguvvala** [comment] 2024-05-20 13:36
@TatsuUkraine @russellwheatley - I am on latest version of flutterfire(1.0.0), I cleaned up my ios project and re ran flutterfire configure cmd, it didnt work.
Every time i run fluttefire configure command, GoogleServiceInfo plist file is being generated, is that expected?

And I am seeing this warning in flutterfire 1.0.0
> Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.

flutterfire build phase script after re running, this needs to be removed or this is correct script?
```
#!/bin/bash
PATH=${PATH}:$FLUTTER_ROOT/bin:$HOME/.pub-cache/bin
flutterfire upload-crashlytics-symbols --upload-symbols-script-path=$PODS_ROOT/FirebaseCrashlytics/upload-symbols --platform=ios --apple-project-path=${SRCROOT} --env-platform-name=${PLATFORM_NAME} --env-configuration=${CONFIGURATION} --env-project-dir=${PROJECT_DIR} --env-built-products-dir=${BUILT_PRODUCTS_DIR} --env-dwarf-dsym-folder-path=${DWARF_DSYM_FOLDER_PATH} --env-dwarf-dsym-file-name=${DWARF_DSYM_FILE_NAME} --env-infoplist-path=${INFOPLIST_PATH} --default-config=default
```
